<div class='cardoption'><div id='row'><div class='well'>
<div class='row'>
<div class='col-sm-3'><label for='catid'>Category:</label>
<select id='catid' style='width: 100%;' name='catid' onchange="showpage('./dumps.php?cat='+document.getElementById('catid').options[document.getElementById('catid').selectedIndex].value+'&bin='+document.getElementById('cardbin').value+'&page=1&perpage='+document.getElementById('cardPerPage').options[document.getElementById('cardPerPage').selectedIndex].value);">
<option {% if categoryId == '0' %} selected {% endif %} value="0">All</option>
{% for category in listCategory %}
<option {% if categoryId == category.categoryId %} selected {% endif %}
value='{{category.categoryId}}'>{{category.categoryName}}</option>
{% endfor %}
</select></div>
<div class='col-sm-3'><label for='cardbin'>Bin:</label><div class='input-group' style='margin-top:3px;'><input  type='hidden' id='cardbin' style='width: 100%;' value="{{get['bin']}}" /> <span class='input-group-btn'><button type='button' onclick="showpage('./dumps.php?cat='+document.getElementById('catid').options[document.getElementById('catid').selectedIndex].value+'&bin='+document.getElementById('cardbin').value+'&last4='+document.getElementById('last4').value+'&type='+document.getElementById('type').options[document.getElementById('type').selectedIndex].value+'&code='+document.getElementById('code').options[document.getElementById('code').selectedIndex].value+'&level='+document.getElementById('level').options[document.getElementById('level').selectedIndex].value+'&class='+document.getElementById('class').options[document.getElementById('class').selectedIndex].value+'&country='+document.getElementById('cardcountry').value+'&bank='+document.getElementById('bank').options[document.getElementById('bank').selectedIndex].value+'&page=1&perpage='+document.getElementById('cardPerPage').options[document.getElementById('cardPerPage').selectedIndex].value);" class='btn btn-default'><i class='fa fa-angle-double-right'></i> Go!</button></span> </div>
</div><div class='col-sm-3'><label for='last4'>Last 4:</label><input class='form-control' id='last4' style='width: 100%; margin-top:3px;' value="{{get['last4'] | slice(0,7)}}" size="4" onchange="showpage('./dumps.php?cat='+document.getElementById('catid').options[document.getElementById('catid').selectedIndex].value+'&bin='+document.getElementById('cardbin').value+'&last4='+document.getElementById('last4').value+'&type='+document.getElementById('type').options[document.getElementById('type').selectedIndex].value+'&code='+document.getElementById('code').options[document.getElementById('code').selectedIndex].value+'&level='+document.getElementById('level').options[document.getElementById('level').selectedIndex].value+'&class='+document.getElementById('class').options[document.getElementById('class').selectedIndex].value+'&country='+document.getElementById('cardcountry').value+'&bank='+document.getElementById('bank').options[document.getElementById('bank').selectedIndex].value+'&page=1&perpage='+document.getElementById('cardPerPage').options[document.getElementById('cardPerPage').selectedIndex].value);" maxlength="4" />
</div><div class='col-sm-3'><label for='type'>Type:</label><select id='type' style='width: 100%;' name='type' onchange="showpage('./dumps.php?cat='+document.getElementById('catid').options[document.getElementById('catid').selectedIndex].value+'&bin='+document.getElementById('cardbin').value+'&last4='+document.getElementById('last4').value+'&type='+document.getElementById('type').options[document.getElementById('type').selectedIndex].value+'&code='+document.getElementById('code').options[document.getElementById('code').selectedIndex].value+'&level='+document.getElementById('level').options[document.getElementById('level').selectedIndex].value+'&class='+document.getElementById('class').options[document.getElementById('class').selectedIndex].value+'&country='+document.getElementById('cardcountry').options[document.getElementById('cardcountry').selectedIndex].value+'&bank='+document.getElementById('bank').options[document.getElementById('bank').selectedIndex].value+'&page=1&perpage='+document.getElementById('cardPerPage').options[document.getElementById('cardPerPage').selectedIndex].value);">
<option {% if instype == '0' %} selected {% endif %} value="">All</option>
{% for itype in listtype %}
<option {% if instype == itype.dumptype %} selected {% endif %}
value='{{itype.dumptype}}'>{{itype.dumptype}} ({{itype.count}})</option>
{% endfor %}
</select></div></div>
<div class='row' style='margin-top:10px'><div class='col-sm-3'><label for='code'>Code:</label><select id='code' style='width: 100%;' name='code' onchange="showpage('./dumps.php?cat='+document.getElementById('catid').options[document.getElementById('catid').selectedIndex].value+'&bin='+document.getElementById('cardbin').value+'&last4='+document.getElementById('last4').value+'&type='+document.getElementById('type').options[document.getElementById('type').selectedIndex].value+'&code='+document.getElementById('code').options[document.getElementById('code').selectedIndex].value+'&level='+document.getElementById('level').options[document.getElementById('level').selectedIndex].value+'&class='+document.getElementById('class').options[document.getElementById('class').selectedIndex].value+'&country='+document.getElementById('cardcountry').options[document.getElementById('cardcountry').selectedIndex].value+'&bank='+document.getElementById('bank').options[document.getElementById('bank').selectedIndex].value+'&page=1&perpage='+document.getElementById('cardPerPage').options[document.getElementById('cardPerPage').selectedIndex].value);">
<option {% if inscode == '0' %} selected {% endif %} value="">All</option>
{% for icode in listcode %}
<option {% if inscode == icode.dumpcode %} selected {% endif %}
value='{{icode.dumpcode}}'>{{icode.dumpcode}} ({{icode.count}})</option>
{% endfor %}
</select></div>
<div class='col-sm-3'><label for='level'>Level:</label><select id='level' style='width: 100%;' name='level' onchange="showpage('./dumps.php?cat='+document.getElementById('catid').options[document.getElementById('catid').selectedIndex].value+'&bin='+document.getElementById('cardbin').value+'&last4='+document.getElementById('last4').value+'&type='+document.getElementById('type').options[document.getElementById('type').selectedIndex].value+'&code='+document.getElementById('code').options[document.getElementById('code').selectedIndex].value+'&level='+document.getElementById('level').options[document.getElementById('level').selectedIndex].value+'&class='+document.getElementById('class').options[document.getElementById('class').selectedIndex].value+'&country='+document.getElementById('cardcountry').options[document.getElementById('cardcountry').selectedIndex].value+'&bank='+document.getElementById('bank').options[document.getElementById('bank').selectedIndex].value+'&page=1&perpage='+document.getElementById('cardPerPage').options[document.getElementById('cardPerPage').selectedIndex].value);">
<option {% if inslevel == '0' %} selected {% endif %} value="">All</option>
{% for ilevel in listlevel %}
<option {% if inslevel == ilevel.dumplevel %} selected {% endif %}
value='{{ilevel.dumplevel}}'>{{ilevel.dumplevel}} ({{ilevel.count}})</option>
{% endfor %}
</select></div>
<div class='col-sm-3'><label for='class'>Class:</label><select id='class' style='width: 100%;' name='class' onchange="showpage('./dumps.php?cat='+document.getElementById('catid').options[document.getElementById('catid').selectedIndex].value+'&bin='+document.getElementById('cardbin').value+'&last4='+document.getElementById('last4').value+'&type='+document.getElementById('type').options[document.getElementById('type').selectedIndex].value+'&code='+document.getElementById('code').options[document.getElementById('code').selectedIndex].value+'&level='+document.getElementById('level').options[document.getElementById('level').selectedIndex].value+'&class='+document.getElementById('class').options[document.getElementById('class').selectedIndex].value+'&country='+document.getElementById('cardcountry').options[document.getElementById('cardcountry').selectedIndex].value+'&bank='+document.getElementById('bank').options[document.getElementById('bank').selectedIndex].value+'&page=1&perpage='+document.getElementById('cardPerPage').options[document.getElementById('cardPerPage').selectedIndex].value);">
<option {% if insclass == '0' %} selected {% endif %} value="">All</option>
{% for iclass in listclass %}
<option {% if insclass == iclass.dumpclass %} selected {% endif %}
value='{{iclass.dumpclass}}'>{{iclass.dumpclass}} ({{iclass.count}})</option>
{% endfor %}
</select></div>
<div class='col-sm-3'><label for='cardcountry'>Country:</label><select id='cardcountry' style='width: 100%;' name='cardcountry' onchange="showpage('./dumps.php?cat='+document.getElementById('catid').options[document.getElementById('catid').selectedIndex].value+'&bin='+document.getElementById('cardbin').value+'&last4='+document.getElementById('last4').value+'&type='+document.getElementById('type').options[document.getElementById('type').selectedIndex].value+'&code='+document.getElementById('code').options[document.getElementById('code').selectedIndex].value+'&level='+document.getElementById('level').options[document.getElementById('level').selectedIndex].value+'&class='+document.getElementById('class').options[document.getElementById('class').selectedIndex].value+'&country='+document.getElementById('cardcountry').options[document.getElementById('cardcountry').selectedIndex].value+'&bank='+document.getElementById('bank').options[document.getElementById('bank').selectedIndex].value+'&page=1&perpage='+document.getElementById('cardPerPage').options[document.getElementById('cardPerPage').selectedIndex].value);">
<option {% if inscountry == '0' %} selected {% endif %} value="">All</option>
{% for icountry in listCou %}
<option {% if inscountry == icountry.dumpCou %} selected {% endif %}
value='{{icountry.dumpCou}}'>{{icountry.dumpCou}} ({{icountry.count}})</option>
{% endfor %}
</select></div></div>
<div class='row' style='margin-top:10px'><div class='col-sm-3'><label for='bank'>Bank:</label><select id='bank' style='width: 100%;' name='bank' onchange="showpage('./dumps.php?cat='+document.getElementById('catid').options[document.getElementById('catid').selectedIndex].value+'&bin='+document.getElementById('cardbin').value+'&last4='+document.getElementById('last4').value+'&type='+document.getElementById('type').options[document.getElementById('type').selectedIndex].value+'&code='+document.getElementById('code').options[document.getElementById('code').selectedIndex].value+'&level='+document.getElementById('level').options[document.getElementById('level').selectedIndex].value+'&class='+document.getElementById('class').options[document.getElementById('class').selectedIndex].value+'&country='+document.getElementById('cardcountry').options[document.getElementById('cardcountry').selectedIndex].value+'&bank='+document.getElementById('bank').options[document.getElementById('bank').selectedIndex].value+'&page=1&perpage='+document.getElementById('cardPerPage').options[document.getElementById('cardPerPage').selectedIndex].value);">
<option {% if insbank == '0' %} selected {% endif %} value="">All</option>
{% for ibank in listbank %}
<option {% if insbank == ibank.dumpbank %} selected {% endif %}
value='{{ibank.dumpbank}}'>{{ibank.dumpbank}} ({{ibank.count}})</option>
{% endfor %}
</select></div>
<div class='col-sm-3'><label for='showUsed'>Show:</label><select id='showUsed' style='width: 100%; margin-bottom:10px;' name='showUsed' onchange="showpage('./dumps.php?cat='+document.getElementById('catid').options[document.getElementById('catid').selectedIndex].value+'&bin='+document.getElementById('cardbin').value+'&last4='+document.getElementById('last4').value+'&type='+document.getElementById('type').options[document.getElementById('type').selectedIndex].value+'&code='+document.getElementById('code').options[document.getElementById('code').selectedIndex].value+'&level='+document.getElementById('level').options[document.getElementById('level').selectedIndex].value+'&class='+document.getElementById('class').options[document.getElementById('class').selectedIndex].value+'&country='+document.getElementById('cardcountry').options[document.getElementById('cardcountry').selectedIndex].value+'&bank='+document.getElementById('bank').options[document.getElementById('bank').selectedIndex].value+'&page=1&perpage='+document.getElementById('cardPerPage').options[document.getElementById('cardPerPage').selectedIndex].value+'&showused='+document.getElementById('showUsed').options[document.getElementById('showUsed').selectedIndex].value);">
<option {% if showused == 'no' %} selected {% endif %} value="no">Unused</option>
<option {% if showused == 'yes' %} selected {% endif %} value="yes">Used</option>
<option {% if showused == 'all' %} selected {% endif %} value="all">All</option>
</select></div>
<div class='col-sm-3'><label for='cardPerPage'>Dumps per page:</label><select id='cardPerPage' style='width: 100%; margin-bottom:10px;' name='cardPerPage' onchange="showpage('./dumps.php?cat='+document.getElementById('catid').options[document.getElementById('catid').selectedIndex].value+'&bin='+document.getElementById('cardbin').value+'&last4='+document.getElementById('last4').value+'&type='+document.getElementById('type').options[document.getElementById('type').selectedIndex].value+'&code='+document.getElementById('code').options[document.getElementById('code').selectedIndex].value+'&level='+document.getElementById('level').options[document.getElementById('level').selectedIndex].value+'&class='+document.getElementById('class').options[document.getElementById('class').selectedIndex].value+'&country='+document.getElementById('cardcountry').options[document.getElementById('cardcountry').selectedIndex].value+'&bank='+document.getElementById('bank').options[document.getElementById('bank').selectedIndex].value+'&page=1&perpage='+document.getElementById('cardPerPage').options[document.getElementById('cardPerPage').selectedIndex].value);">
<option {% if cardPerPage == '10' %} selected {% endif %} value="10">10</option>
<option {% if cardPerPage == '20' %} selected {% endif %} value="20">20</option>
<option {% if cardPerPage == '50' %} selected {% endif %} value="50">50</option>
<option {% if cardPerPage == '100' %} selected {% endif %} value="100">100</option>
</select></div>
<div class='col-sm-3'><label for='cardpage'>Page:</label><select id='cardpage' style='width: 100%;' name='cardpage' onchange="showpage('./dumps.php?cat='+document.getElementById('catid').options[document.getElementById('catid').selectedIndex].value+'&bin='+document.getElementById('cardbin').value+'&last4='+document.getElementById('last4').value+'&type='+document.getElementById('type').options[document.getElementById('type').selectedIndex].value+'&code='+document.getElementById('code').options[document.getElementById('code').selectedIndex].value+'&level='+document.getElementById('level').options[document.getElementById('level').selectedIndex].value+'&class='+document.getElementById('class').options[document.getElementById('class').selectedIndex].value+'&country='+document.getElementById('cardcountry').options[document.getElementById('cardcountry').selectedIndex].value+'&bank='+document.getElementById('bank').options[document.getElementById('bank').selectedIndex].value+'&page='+document.getElementById('cardpage').options[document.getElementById('cardpage').selectedIndex].value+'&perpage='+document.getElementById('cardPerPage').options[document.getElementById('cardPerPage').selectedIndex].value);">
<option {% if currentPage == '1' %} selected {% endif %} value="1">1</option>
{% if pages > '1' %}
{% for i in range(2, pages) %}
<option {% if currentPage == i %} selected {% endif %} value="{{i}}">{{i}}</option>
{% endfor %}
{% endif %}
</select></div>
</div></div></div></div>